on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: echo
        working-directory: Users_files
        run: |
          echo ${{ vars.VAR_1 }}
      - run: exit 0