on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string

defaults:
  run:
    working-directory: Users_files

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: echo
        run: |
          echo ${{ vars.VAR_1 }}
      - name: echo2
        run: |
          echo ${{ secrets.VAR_S_1 }}
      - name: echo3
        run: |
          ls -la
      - name: echo4
        working-directory: Users_files/tmp
        run: |
          ls -la
      - run: exit 0
      - run: exit 0