name: push
on:
  push:
    branches:
      - main
    paths:
      - 'Users_files/**'
jobs:
  push-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: ./.github/workflows/deploy.yaml
      - run: exit 0
  push-qa:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: ./.github/workflows/deploy.yaml
      - run: exit 0