name: push
on:
  push:
    branches:
      - main
    paths:
      - 'Users_files/**'
jobs:
  push-dev:
    uses: ./.github/workflows/deploy.yaml
    with:
      ENV_NAME: DEV
  push-qa:
    uses: ./.github/workflows/deploy.yaml
    with:
      ENV_NAME: QA