name: push-casc-terraform
on:
  push:
    branches:
      - main
    paths:
      - 'Users_files/**'
jobs:
  push-casc-terraform:
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: echo
        working-directory: Users_files
        run: |
          echo ${{ vars.VAR_1 }}
      - run: exit 0
